# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import number_guesser_pb2 as number__guesser__pb2


class NumberGuesserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StartGame = channel.unary_unary(
        '/NumberGuesser/StartGame',
        request_serializer=number__guesser__pb2.StartGameRequest.SerializeToString,
        response_deserializer=number__guesser__pb2.StartGameResponse.FromString,
        )
    self.Guess = channel.unary_unary(
        '/NumberGuesser/Guess',
        request_serializer=number__guesser__pb2.GuessRequest.SerializeToString,
        response_deserializer=number__guesser__pb2.GuessResponse.FromString,
        )


class NumberGuesserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StartGame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Guess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NumberGuesserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StartGame': grpc.unary_unary_rpc_method_handler(
          servicer.StartGame,
          request_deserializer=number__guesser__pb2.StartGameRequest.FromString,
          response_serializer=number__guesser__pb2.StartGameResponse.SerializeToString,
      ),
      'Guess': grpc.unary_unary_rpc_method_handler(
          servicer.Guess,
          request_deserializer=number__guesser__pb2.GuessRequest.FromString,
          response_serializer=number__guesser__pb2.GuessResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NumberGuesser', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
