# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rservice.proto\"3\n\x10StartGameRequest\x12\x1f\n\ndifficulty\x18\x01 \x01(\x0e\x32\x0b.Difficulty\"B\n\x11StartGameResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\r\n\x05lower\x18\x02 \x01(\r\x12\r\n\x05upper\x18\x03 \x01(\r\".\n\x0cGuessRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\r\n\x05guess\x18\x02 \x01(\r\"-\n\rGuessResponse\x12\x1c\n\x06result\x18\x01 \x01(\x0e\x32\x0c.GuessResult*i\n\nDifficulty\x12\x1a\n\x16\x44IFFICULTY_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x44IFFICULTY_EASY\x10\x01\x12\x15\n\x11\x44IFFICULTY_MEDIUM\x10\x02\x12\x13\n\x0f\x44IFFICULTY_HARD\x10\x03*O\n\x0bGuessResult\x12\x16\n\x12RESULT_UNSPECIFIED\x10\x00\x12\x14\n\x10RESULT_INCORRECT\x10\x01\x12\x12\n\x0eRESULT_CORRECT\x10\x02\x32k\n\rNumberGuesser\x12\x32\n\tStartGame\x12\x11.StartGameRequest\x1a\x12.StartGameResponse\x12&\n\x05Guess\x12\r.GuessRequest\x1a\x0e.GuessResponseb\x06proto3')
)

_DIFFICULTY = _descriptor.EnumDescriptor(
  name='Difficulty',
  full_name='Difficulty',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIFFICULTY_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIFFICULTY_EASY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIFFICULTY_MEDIUM', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIFFICULTY_HARD', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=233,
  serialized_end=338,
)
_sym_db.RegisterEnumDescriptor(_DIFFICULTY)

Difficulty = enum_type_wrapper.EnumTypeWrapper(_DIFFICULTY)
_GUESSRESULT = _descriptor.EnumDescriptor(
  name='GuessResult',
  full_name='GuessResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESULT_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESULT_INCORRECT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CORRECT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=340,
  serialized_end=419,
)
_sym_db.RegisterEnumDescriptor(_GUESSRESULT)

GuessResult = enum_type_wrapper.EnumTypeWrapper(_GUESSRESULT)
DIFFICULTY_UNSPECIFIED = 0
DIFFICULTY_EASY = 1
DIFFICULTY_MEDIUM = 2
DIFFICULTY_HARD = 3
RESULT_UNSPECIFIED = 0
RESULT_INCORRECT = 1
RESULT_CORRECT = 2



_STARTGAMEREQUEST = _descriptor.Descriptor(
  name='StartGameRequest',
  full_name='StartGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='difficulty', full_name='StartGameRequest.difficulty', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=68,
)


_STARTGAMERESPONSE = _descriptor.Descriptor(
  name='StartGameResponse',
  full_name='StartGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='StartGameResponse.game_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lower', full_name='StartGameResponse.lower', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upper', full_name='StartGameResponse.upper', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=136,
)


_GUESSREQUEST = _descriptor.Descriptor(
  name='GuessRequest',
  full_name='GuessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='GuessRequest.game_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='guess', full_name='GuessRequest.guess', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=184,
)


_GUESSRESPONSE = _descriptor.Descriptor(
  name='GuessResponse',
  full_name='GuessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='GuessResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=231,
)

_STARTGAMEREQUEST.fields_by_name['difficulty'].enum_type = _DIFFICULTY
_GUESSRESPONSE.fields_by_name['result'].enum_type = _GUESSRESULT
DESCRIPTOR.message_types_by_name['StartGameRequest'] = _STARTGAMEREQUEST
DESCRIPTOR.message_types_by_name['StartGameResponse'] = _STARTGAMERESPONSE
DESCRIPTOR.message_types_by_name['GuessRequest'] = _GUESSREQUEST
DESCRIPTOR.message_types_by_name['GuessResponse'] = _GUESSRESPONSE
DESCRIPTOR.enum_types_by_name['Difficulty'] = _DIFFICULTY
DESCRIPTOR.enum_types_by_name['GuessResult'] = _GUESSRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartGameRequest = _reflection.GeneratedProtocolMessageType('StartGameRequest', (_message.Message,), dict(
  DESCRIPTOR = _STARTGAMEREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:StartGameRequest)
  ))
_sym_db.RegisterMessage(StartGameRequest)

StartGameResponse = _reflection.GeneratedProtocolMessageType('StartGameResponse', (_message.Message,), dict(
  DESCRIPTOR = _STARTGAMERESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:StartGameResponse)
  ))
_sym_db.RegisterMessage(StartGameResponse)

GuessRequest = _reflection.GeneratedProtocolMessageType('GuessRequest', (_message.Message,), dict(
  DESCRIPTOR = _GUESSREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:GuessRequest)
  ))
_sym_db.RegisterMessage(GuessRequest)

GuessResponse = _reflection.GeneratedProtocolMessageType('GuessResponse', (_message.Message,), dict(
  DESCRIPTOR = _GUESSRESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:GuessResponse)
  ))
_sym_db.RegisterMessage(GuessResponse)



_NUMBERGUESSER = _descriptor.ServiceDescriptor(
  name='NumberGuesser',
  full_name='NumberGuesser',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=421,
  serialized_end=528,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartGame',
    full_name='NumberGuesser.StartGame',
    index=0,
    containing_service=None,
    input_type=_STARTGAMEREQUEST,
    output_type=_STARTGAMERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Guess',
    full_name='NumberGuesser.Guess',
    index=1,
    containing_service=None,
    input_type=_GUESSREQUEST,
    output_type=_GUESSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NUMBERGUESSER)

DESCRIPTOR.services_by_name['NumberGuesser'] = _NUMBERGUESSER

# @@protoc_insertion_point(module_scope)
